os: linux
dist: xenial
language: node_js
env: NODE_ENV=development
node_js:
  - lts/*
cache:
  directories:
    - '$HOME/.npm'
before_install:
  - openssl aes-256-cbc -K $encrypted_4b4244bfbb7a_key -iv $encrypted_4b4244bfbb7a_iv
    -in travis.key.enc -out travis.key -d
  - sudo apt-get update
  - sudo apt-get install git-crypt
  - git-crypt unlock travis.key
install:
  - npm ci
script: npm run verifyCi
